global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'eth_deposit_tracker'
    static_configs:
      - targets: ['host.docker.internal:9101']  # Assuming your app exposes metrics on port 9101