global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'eth_deposit_tracker'
    static_configs:
      - targets: ['host.docker.internal:9101']  # Your app metrics

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']  # System metrics from node_exporter