{
 "title": "ETH_DEPOSIT_TRACKER",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "rate(eth_total_deposits[5m])",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(eth_total_deposits[5m])" }
   ]
  },
  {
   "title": "eth_total_amount_deposited",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "eth_total_amount_deposited" }
   ]
  },
  {
   "title": "eth_total_deposits",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "eth_total_deposits" }
   ]
  }
 ]
}